#!/bin/bash

robot_host="robik"
source /opt/ros/indigo/setup.bash
source /home/honza/workspace/devel/setup.bash


#------ end of user defined config --------

amixer set Speaker playback 100% unmute

#nechapu, proc se festival zasekne
#echo "Startuji" | festival --tts --language czech

echo "*******************"
if lsusb | grep --quiet 2341:0010 ; then
    export CONNECTED="true"
    echo "Arduino IS connected"
else
    export CONNECTED="false"
    echo "Arduino is NOT connected"
fi
echo "*******************"

export ROS_MASTER_URI=http://$robot_host:11311/
export ROS_HOSTNAME=$robot_host

cd /home/honza/workspace/src/robik/launch
roslaunch robik.launch


